### ISSUE TITLE
Add screenshot to readme

### ISSUE THREAD

**Issue by jakenvac** [doums/monark.nvim#3]
This sounds like a really great plugin, with it being very much based on a visual component of nvim I think it would be a good idea to have a screenshot in the readme.

**Comment by l00sed** [comment]
Totally agree! I'm watching the repo, waiting for the screenshot or recording. It sounds awesome, but I don't want to pull it and try it out just to find out it's not what I'm picturing in my head. There are a lot of good tools that you can use to accomplish a recording: https://github.com/faressoft/terminalizer

Sounds like a good tool, please give us a visual!

**Comment by doums** [comment]
You're free to open a PR and provide one, if spending literally ~2min of trying the plugin yourself is bothering you. Or keep waiting as long as you want if it's a better solution that trying it directly, lol.

**Comment by l00sed** [comment]
Not trying to be rude or complain, I'm really stoked to see new Neovim plugins and developers who take the time to do the work. The criticism is valuable criticism-- if you're interested in people using this tool, offering a visual demo to your repo would likely encourage more people (2, at the very least) to do so. 🤷

**Comment by doums** [comment]
Wasting your time (and bother mine) by commenting issue and waiting instead of contributing yourself either by testing the plugin directly or even better creating this demo screen capture that you want so much and share it. In an open source perspective, it is complaining.
